# Tuan Le
# University of California, Berkeley
# Berkeley Space Sciences Lab
# tuanle86@berkeley.edu

# Add source files here
EXECUTABLE	:= example_app_nvopencl
# C/C++ source files (compiled with gcc / c++)
CCFILES		:= nvopencl.cpp

################################################################################
# Rules and targets

include common_opencl.mk


