# Tuan Le
# University of California, Berkeley
# Berkeley Space Sciences Lab
# tuanle86@berkeley.ed

# Add source files here
EXECUTABLE	:= example_app_nvcuda
# Cuda source files (compiled with cudacc)
CUFILES		:= cuda.cu
# C/C++ source files (compiled with gcc / c++)
CCFILES		:= \

################################################################################
# Rules and targets

include common.mk
