#! /bin/tcsh

../tools/create_work -appname concat -wu_name concat_wu -wu_template concat_wu -result_template concat_result -nresults 2 input input
../tools/create_work -appname upper_case -wu_name uc_wu -wu_template uc_wu -result_template uc_result -nresults 2 input input
