build:
    environment:
        php: 7.4
    nodes:
        analysis:
            dependencies:
                before:
                    - command: 'mkdir -p 3rdParty/buildCache && wget https://ftp.drupal.org/files/projects/drupal-6.38.tar.gz -O drupal-6.38.tar.gz && tar -C 3rdParty/buildCache/ -xzf drupal-6.38.tar.gz'
                      not_if: 'test -e 3rdParty/buildCache/drupal-6.38'
            cache:
                disabled: false
                directories:
                    - '3rdParty/buildCache'
            tests:
                override:
                    - php-scrutinizer-run
                    - js-scrutinizer-run
filter:
    paths:
        - 'html/*.php'
        - 'html/*.inc'
        - 'py/*'
        - 'tools/*'
        - 'drupal/*'
    excluded_paths:
        - '*.tpl.php'
        - '*.min.js'
        - 'drupal/sites/default/modules/boinc/*'
        - 'drupal/sites/default/themes/boinc/*'
        - 'tests/server-test/*'
    dependency_paths:
        - 'html/inc/htmLawed.php'
        - 'drupal/sites/all/libraries/*'
        - 'drupal/sites/default/boinc/modules/contrib/*'
        - 'drupal/sites/default/boinc/modules/boincstats/includes/pchart/*'
        - 'drupal/sites/all/libraries/phpmailer/*'
        - '3rdParty/buildCache/drupal-6.38/*'
checks:
    php:
        fix_php_opening_tag: false
        remove_php_closing_tag: false
        one_class_per_file: false
        side_effects_or_types: false
        no_mixed_inline_html: false
        require_braces_around_control_structures: false
        php5_style_constructor: false
        no_global_keyword: false
        avoid_usage_of_logical_operators: false
        psr2_class_declaration: false
        no_underscore_prefix_in_properties: false
        no_underscore_prefix_in_methods: false
        blank_line_after_namespace_declaration: false
        single_namespace_per_use: false
        psr2_switch_declaration: false
        psr2_control_structure_declaration: false
        avoid_superglobals: false
        security_vulnerabilities: false
        no_exit: false
    javascript: true
