build:
    environment:
        php: 7.4
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
                    - js-scrutinizer-run
filter:
    paths:
        - 'html/*.php'
        - 'html/*.inc'
        - 'py/*'
        - 'tools/*'
    excluded_paths:
        - '*.tpl.php'
        - '*.min.js'
        - 'tests/server-test/*'
    dependency_paths:
        - 'html/inc/htmLawed.php'
checks:
    php:
        fix_php_opening_tag: false
        remove_php_closing_tag: false
        one_class_per_file: false
        side_effects_or_types: false
        no_mixed_inline_html: false
        require_braces_around_control_structures: false
        php5_style_constructor: false
        no_global_keyword: false
        avoid_usage_of_logical_operators: false
        psr2_class_declaration: false
        no_underscore_prefix_in_properties: false
        no_underscore_prefix_in_methods: false
        blank_line_after_namespace_declaration: false
        single_namespace_per_use: false
        psr2_switch_declaration: false
        psr2_control_structure_declaration: false
        avoid_superglobals: false
        security_vulnerabilities: false
        no_exit: false
    javascript: true
