#!/bin/sh

## $Id$

# for solaris machines that don't have autoconf 2.57 or automake 1.7 installed:

# this file is only for bootstrapping the "Makefile.in" files and "Makefile"
# files; you probably don't need to run this if the Makefile.in files were
# correctly checked into the repository.

## need autoconf, automake, m4, ... from quarl's bin directory:
if [ `uname` = SunOS ]; then
	PATH=/disks/philmor/a/users/quarl/local/Node-SOLARIS/bin:$PATH
	export PATH
fi

if [ -d autom4te.cache ]; then
  /bin/rm -rf autom4te.cache
fi

echo "Bootstrapping configure script and makefiles:"

ACLOCAL=aclocal
AUTOHEADER=autoheader
AUTOMAKE=automake
AUTOCONF=autoconf

if $ACLOCAL -I m4 && $AUTOHEADER && $AUTOMAKE && $AUTOCONF; then
    ## We don't always run ./configure ourselves here, because the user may not
   ## want to run it, or may want to run with custom parameters.

    if [ "$1" = "-a" ]; then
	./configure -C --enable-maintainer-mode
    elif [ "$1" = "-c" ]; then
	./configure -C
    else
	echo "Done, now run ./configure"
	echo " ./configure -C                         to enable caching"
	echo " ./configure --enable-maintainer-mode   to enable maintainer depedencies"
	exit 0
    fi
else
    echo "Something failed .... please check error-message and re-run when fixed."
    echo "exiting..."
    exit 1
fi
