/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */


/* double-inclusion protection for config.h */
#ifndef BOINC_CONFIG_H
#define BOINC_CONFIG_H

#include "version.h"

#ifdef _WIN32
#include "win_config.h"
#else

#error "You need to run configure first!"

#endif /* #ifndef _WIN32 */
/* end double-inclusion protection for config.h */
#endif /* #ifndef BOINC_CONFIG_H */

