# This file is part of BOINC.
# https://boinc.berkeley.edu
# Copyright (C) 2026 University of California
#
# BOINC is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License
# as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
#
# BOINC is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with BOINC.  If not, see <http://www.gnu.org/licenses/>.
#

# For debugging purposes
#AM_DEFAULT_VERBOSITY=1

# Note: MYSQL_CFLAGS and MYSQL_LIBS set by configure from mysql_config

# ignore any LIBS set by configure
LIBS=

LIBBOINC_VERSION = @LIBBOINC_VERSION@

MYSQL_LIBS = @MYSQL_LIBS@
MYSQL_CFLAGS = @MYSQL_CFLAGS@
PTHREAD_CFLAGS = @PTHREAD_CFLAGS@
PTHREAD_LIBS = @PTHREAD_LIBS@

RSA_LIBS = -lcrypto

AM_LIBTOOLFLAGS =

AM_CPPFLAGS =					\
        -I$(top_srcdir)				\
        -I$(top_srcdir)/api			\
        -I$(top_srcdir)/db			\
        -I$(top_srcdir)/lib			\
        -I$(top_srcdir)/lib/mac			\
        -I$(top_srcdir)/sched			\
        -I$(top_srcdir)/tools			\
        -I$(top_srcdir)/vda			\
	$(PTHREAD_CFLAGS)

AM_CFLAGS = -Wall -Wextra -Wpedantic -Wshadow -Wredundant-decls -Wdisabled-optimization -Wcast-align

AM_CXXFLAGS = $(AM_CFLAGS)

AM_LDFLAGS =

LIBSCHED = $(top_builddir)/sched/libsched.la
LIBSCHED_FCGI = $(top_builddir)/sched/libsched_fcgi.la
LIBBOINC = $(top_builddir)/lib/libboinc.la
LIBBOINC_CRYPT = $(top_builddir)/lib/libboinc_crypt.la
LIBBOINC_FCGI = $(top_builddir)/lib/libboinc_fcgi.la
LIBAPI = $(top_builddir)/api/libboinc_api.la

SERVERLIBS = $(LIBSCHED) $(LIBBOINC_CRYPT) $(LIBBOINC) $(MYSQL_LIBS) $(PTHREAD_LIBS) $(RSA_LIBS) $(SSL_LIBS)
SERVERLIBS_MIN = $(LIBSCHED) $(LIBBOINC_CRYPT) $(LIBBOINC) $(PTHREAD_LIBS) $(RSA_LIBS) $(SSL_LIBS)
APPLIBS = $(LIBAPI) $(LIBBOINC)
FUHLIBS = $(LIBBOINC_CRYPT) $(LIBBOINC) $(RSA_LIBS) $(SSL_LIBS)
FUHLIBS_FCGI = $(LIBBOINC_CRYPT) $(LIBBOINC_FCGI) -lfcgi $(RSA_LIBS) $(SSL_LIBS)
