#!/bin/sh

## $Id$

# Create a nightly tarball from CVS export

# need to set PATH because we might be running from a cron job.
# on our Solaris servers, cvs is in /opt/misc/bin

cd $HOME/boinc

if [ -d /disks/asimov ]; then
    PATH=/disks/philmor/a/users/quarl/local/Node-SOLARIS/bin:/disks/philmor/a/users/quarl/local/bin:/disks/philmor/a/users/quarl/bin:/usr/ccs/bin:/usr/local/cygnus:/disks/milkyway/a/users/anderson/seti/bin:/opt/misc/bin:/usr/ucb:/usr/bin:/usr/local/bin
    export PATH
fi

    CVS_RSH=/usr/bin/ssh \
    CVSROOT=:ext:boincadm@milkyway.ssl.berkeley.edu:/usr/local/warez/cvsroot \
    CHECKOUT='cvs export -r HEAD boinc && (cd boinc && ./_autosetup)'          \
    DIR=boinc                                                                  \
    FILENAME_TGZ="boinc-cvs-TODAY.tar.gz"                                      \
    FILENAME_ZIP="boinc-cvs-TODAY.zip"                                         \
    DESTINATION="/home/boincadm/boinc/doc/source/nightly/"   \
    ./export-tarball

    CVS_RSH=/usr/bin/ssh \
    CVSROOT=:ext:boincadm@milkyway.ssl.berkeley.edu:/usr/local/warez/cvsroot \
    CHECKOUT='cvs export -r stable boinc && (cd boinc && ./_autosetup)' \
    DIR=boinc \
    FILENAME_TGZ="boinc_stable-cvs-TODAY.tar.gz"                               \
    FILENAME_ZIP="boinc_stable-cvs-TODAY.zip"                                  \
    DESTINATION="/home/boincadm/boinc/doc/source/nightly/"   \
    ./export-tarball
