#!/bin/sh

## $Id$

# Create a nightly tarball from CVS export

# need to set PATH because we might be running from a cron job.
# on our Solaris servers, cvs is in /opt/misc/bin

if [ -d /disks/asimov ]; then
    PATH=/disks/philmor/a/users/quarl/local/Node-SOLARIS/bin:/disks/philmor/a/users/quarl/local/bin:/disks/philmor/a/users/quarl/bin:/usr/ccs/bin:/usr/local/cygnus:/disks/milkyway/a/users/anderson/seti/bin:/opt/misc/bin:/usr/ucb:/usr/bin:/usr/local/bin
    export PATH
fi

CVSROOT=/usr/local/warez/cvsroot                                               \
    CHECKOUT='cvs export boinc'                                                \
    DIR=boinc                                                                  \
    FILENAME_TGZ="boinc-cvs-TODAY.tar.gz"                                      \
    FILENAME_ZIP="boinc-cvs-TODAY.zip"                                         \
    DESTINATION="/disks/milkyway/a/users/anderson/boinc/doc/source/nightly/"   \
    /disks/philmor/a/users/quarl/bin/export-tarball
