#!/usr/bin/env python

# $Id$
# update boinc_cli.rc with version numbers.
# update boinc_dll.rc with version numbers.
# update boinc_gui.rc with version numbers.
# update boinc_ss.rc  with version numbers.

import boinc_path_config
from Boinc.version import *
import os, re

version_string = '%d,%d,0,0' % (MAJOR_VERSION, MINOR_VERSION)
version_string_spaces = '"%d, %d, 0, 0\\\\0"' % (MAJOR_VERSION, MINOR_VERSION)


fn_boinc_cli_rc_old = 'boinc_cli.rc.old'
fn_boinc_cli_rc = 'boinc_cli.rc'

os.rename(fn_boinc_cli_rc, fn_boinc_cli_rc_old)
rc_boinc_cli_old = open(fn_boinc_cli_rc_old)
rc_boinc_cli = open(fn_boinc_cli_rc, 'w')

for line in rc_boinc_cli_old:
    line = re.sub('( +(FILEVERSION|PRODUDUCTVERSION) +).*', '\\1'+version_string, line)
    line = re.sub('( +VALUE "(FileVersion|ProductVersion)", +).*', '\\1'+version_string_spaces, line)
    rc_boinc_cli.write(line)

print "Updated boinc_cli.rc to version %d.%02d" %(MAJOR_VERSION, MINOR_VERSION)




fn_boinc_dll_rc_old = 'boinc_dll.rc.old'
fn_boinc_dll_rc = 'boinc_dll.rc'

os.rename(fn_boinc_dll_rc, fn_boinc_dll_rc_old)
rc_boinc_dll_old = open(fn_boinc_dll_rc_old)
rc_boinc_dll = open(fn_boinc_dll_rc, 'w')

for line in rc_boinc_dll_old:
    line = re.sub('( +(FILEVERSION|PRODUDUCTVERSION) +).*', '\\1'+version_string, line)
    line = re.sub('( +VALUE "(FileVersion|ProductVersion)", +).*', '\\1'+version_string_spaces, line)
    rc_boinc_dll.write(line)

print "Updated boinc_dll.rc to version %d.%02d" %(MAJOR_VERSION, MINOR_VERSION)




fn_boinc_gui_rc_old = 'boinc_gui.rc.old'
fn_boinc_gui_rc = 'boinc_gui.rc'

os.rename(fn_boinc_gui_rc, fn_boinc_gui_rc_old)
rc_boinc_gui_old = open(fn_boinc_gui_rc_old)
rc_boinc_gui = open(fn_boinc_gui_rc, 'w')

for line in rc_boinc_gui_old:
    line = re.sub('( +(FILEVERSION|PRODUDUCTVERSION) +).*', '\\1'+version_string, line)
    line = re.sub('( +VALUE "(FileVersion|ProductVersion)", +).*', '\\1'+version_string_spaces, line)
    rc_boinc_gui.write(line)

print "Updated boinc_gui.rc to version %d.%02d" %(MAJOR_VERSION, MINOR_VERSION)




fn_boinc_ss_rc_old = 'boinc_ss.rc.old'
fn_boinc_ss_rc = 'boinc_ss.rc'

os.rename(fn_boinc_ss_rc, fn_boinc_ss_rc_old)
rc_boinc_ss_old = open(fn_boinc_ss_rc_old)
rc_boinc_ss = open(fn_boinc_ss_rc, 'w')

for line in rc_boinc_ss_old:
    line = re.sub('( +(FILEVERSION|PRODUDUCTVERSION) +).*', '\\1'+version_string, line)
    line = re.sub('( +VALUE "(FileVersion|ProductVersion)", +).*', '\\1'+version_string_spaces, line)
    rc_boinc_ss.write(line)

print "Updated boinc_ss.rc to version %d.%02d" %(MAJOR_VERSION, MINOR_VERSION)
