/* client/win/win_config.h.  Generated by configure.  */
/* Major part of version number */
#define MAJOR_VERSION 1

/* Minor part of version number */
#define MINOR_VERSION 04

/* Version number of package */
#define VERSION "1.04"

