#!/usr/bin/env python

# $Id$
# update boinc_cli.rc with version numbers.

import boinc_path_config
from Boinc.version import *
import os, re

version_string = '%d,%d,0,0' % (MAJOR_VERSION, MINOR_VERSION)
version_string_spaces = '"%d, %d, 0, 0\\\\0"' % (MAJOR_VERSION, MINOR_VERSION)


fn_boinc_cli_rc_old = 'boinc_cli.rc.old'
fn_boinc_cli_rc = 'boinc_cli.rc'

os.rename(fn_boinc_cli_rc, fn_boinc_cli_rc_old)
rc_boinc_cli_old = open(fn_boinc_cli_rc_old)
rc_boinc_cli = open(fn_boinc_cli_rc, 'w')

for line in rc_boinc_cli_old:
    line = re.sub('( +(FILEVERSION|PRODUDUCTVERSION) +).*', '\\1'+version_string, line)
    line = re.sub('( +VALUE "(FileVersion|ProductVersion)", +).*', '\\1'+version_string_spaces, line)
    rc_boinc_cli.write(line)

print "Updated boinc_cli.rc to version %d.%02d" %(MAJOR_VERSION, MINOR_VERSION)

