#! /bin/csh
# NOTE: this must be macro-substituted (for BOINC_DB_NAME)

set CIVDATE = `date "+%Y:%m:%d:%H:%M"`
set UNIXDATE = `perl -e 'print time()'`
set COUNT = `echo "use david_test; select count(*) from $1" | mysql | tail -1`
 
echo $CIVDATE $UNIXDATE $COUNT
