#! /bin/sh

xgettext --from-code=UTF-8 --keyword=_ -C -o BOINC-Manager.pot *.cpp msw/*.cpp mac/*.cpp gtk/*.cpp
 
../tools/compare_pot BOINC-Manager.pot ../locale/templates/BOINC-Manager.pot davea@ssl.berkeley.edu
