CXX = $(shell wx-config --cxx)

# comment out the following as needed
OTHER_LIBS = -lsocket -lnsl

CFLAGS = -g -I ../ -I ../lib  -DNOTASKBAR -DNOCLIPBOARD

PROGRAM = boincmgr

all: $(PROGRAM)

OBJS = \
    BOINCBaseView.o \
    BOINCGUIApp.o \
    BOINCListCtrl.o \
    BOINCTaskCtrl.o \
    DlgAbout.o \
    DlgAttachProject.o \
    DlgConnection.o \
    DlgOptions.o \
    MainDocument.o \
    MainFrame.o \
    stdwx.o \
    ValidateAccountKey.o \
    ValidateURL.o \
    ViewMessages.o \
    ViewProjects.o \
    ViewResources.o \
    ViewTransfers.o \
    ViewWork.o \
    ../lib/gui_rpc_client.o \
    ../lib/parse.o \
    ../lib/mfile.o \
    ../lib/miofile.o \
    ../lib/filesys.o \
    ../lib/util.o

# change the following as needed

#WLIBS = -framework QuickTime -framework IOKit -framework Carbon -framework Cocoa -framework System    -L../../wxMac-2.5.3/lib    -lwx_mac_core-2.5  -lwx_base_carbon-2.5   -lwxtiff-2.5 -lwxjpeg-2.5 -lwxpng-2.5    -lwxexpat-2.5 -framework QuickTime -framework IOKit -framework Carbon -framework Cocoa -framework System  -lz -lpthread -liconv  -framework WebKit

WLIBS = `wx-config --libs`

boincmgr: $(OBJS)
	$(CXX) -o $(PROGRAM) $(OBJS) $(WLIBS) $(OTHER_LIBS)

.cpp.o:
	$(CXX) -c $(CFLAGS) `wx-config --cxxflags` $<

dependencies: *.cpp *.h
	$(CXX) -M $(CFLAGS) `wx-config --cxxflags` *.cpp > dependencies

include dependencies
