CXX = $(shell wx-config --cxx)

# comment out the following as needed
OTHER_LIBS = -lsocket -lnsl

CFLAGS = -g -I ../lib -I .. -DNOTASKBAR -DNOCLIPBOARD

PROGRAM = boincmgr

all: $(PROGRAM)

OBJS = \
    BOINCBaseView.o \
    BOINCGUIApp.o \
    BOINCListCtrl.o \
    BOINCTaskCtrl.o \
    DlgAbout.o \
    DlgAttachProject.o \
    DlgConnection.o \
    DlgOptions.o \
    MainDocument.o \
    MainFrame.o \
    stdwx.o \
    ValidateAccountKey.o \
    ValidateURL.o \
    ViewMessages.o \
    ViewProjects.o \
    ViewResources.o \
    ViewTransfers.o \
    ViewWork.o \
    ../lib/gui_rpc_client.o \
    ../lib/parse.o \
    ../lib/mfile.o \
    ../lib/miofile.o \
    ../lib/filesys.o \
    ../lib/util.o

boincmgr: $(OBJS)
	$(CXX) -o $(PROGRAM) $(OBJS) `wx-config --libs` $(OTHER_LIBS)

.cpp.o:
	$(CXX) -c $(CFLAGS) `wx-config --cxxflags` $<

dependencies: *.cpp *.h
	$(CXX) -M $(CFLAGS) `wx-config --cxxflags` *.cpp > dependencies

include dependencies
