<?php

/**
 * @file
 * Redirect denied pages to the user login form.
 */

/**
 * Implementation of hook_menu().
 */
function r4032login_menu() {
  $items = array();
  $items['r4032login'] = array(
    'page callback' => 'r4032login_redirect',
    'access callback' => 'r4032login_access',
    'type' => MENU_CALLBACK
  );
  $items['admin/settings/r4032login'] = array(
    'title' => 'Redirect 403 to User Login',
    'description' => 'Toggle display of denied message on login page.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('r4032login_admin_settings'),
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration')
  );
  return $items;
}

/**
 * Without an access callback on the menu item for r4032login_redirect,
 * the redirect will be 403 and just have the default access denied page anyway.
 */
function r4032login_access() {
  return TRUE;
}

function r4032login_admin_settings() {
  $form = array();
  $form['r4032login_display_denied_message'] = array(
    '#type' => 'textarea',
    '#title' => t('Display access denied message on login page'),
    '#default_value' => variable_get('r4032login_display_denied_message', 'Access denied. You must login to view this page.')
  );
  $form['r4032login_user_register_message'] = array(
    '#type' => 'textfield',
    '#title' => t('User register message'),
    '#description' => t('The message to display when a logged-in user tries to register another account through the !new_account. Drupal does not allow it, so regular users must log out first. Administrators should create new users in !link.', array('!new_account' => l(t('new account registration form'), 'user/register'), '!link' => l(t('User management'), 'admin/user/user/create'))),
    '#default_value' => variable_get('r4032login_user_register_message', t('You are not authorized to access this page.'))
  );
  $form['r4032login_redirect_authenticated_users_to'] = array(
    '#type' => 'textfield',
    '#title' => t('Rediect authenticated users to'),
    '#description' => t('If an authenticated user tries to access a page they can not, redirect them to the given page. Use &lt;front&gt; for the front page, leave blank for the default access denied page.'),
    '#default_value' => variable_get('r4032login_redirect_authenticated_users_to', ''),
  );
  return system_settings_form($form);
}

/**
 * Implementation of hook_theme().
 */
function r4032login_theme() {
  return array(
    'r4032login_denied' => array(
      'arguments' => array()
    ),
    'r4032login_user_register' => array(
      'arguments' => array()
    )
  );
}

/**
 * MENU_CALLBACK for /4032login
 *
 * Redirect anonymous users from 403 Access Denied pages to the /user/login page
 * with a message explaining that they must login to view the requested page
 * and a query string parameter appended to the url to return after login.
 */
function r4032login_redirect() {
  global $user;
  $redirect = variable_get('r4032login_redirect_authenticated_users_to', '');
  if (user_is_anonymous()) {
    // Only display the message if there is one.
    $message = variable_get('r4032login_display_denied_message', 'Access denied. You must login to view this page.');
    if (!empty($message)) {
      drupal_set_message(t($message), 'error');
    }
    // using drupal_goto() with destination set causes a recursive redirect loop
    header('Location: '. url('user/login', array('query' => drupal_get_destination(), 'absolute' => TRUE)), TRUE, 302);
    exit;
  }
  elseif (!empty($redirect)) {
    header('Location: '. url($redirect));
    exit;
  }
  // checking arg() returns r4032login
  elseif ($_REQUEST['q'] == 'user/register') {
    print theme('page', theme('r4032login_user_register'));
    exit;
  }
  else {
    print theme('page', theme('r4032login_denied'));
    exit;
  }
}

function theme_r4032login_denied() {
  drupal_set_title(t('Access denied'));
  return '<p>'. t('You are not authorized to access this page.') .'</p>';
}

function theme_r4032login_user_register() {
  drupal_set_title(t('Access denied'));
  $message = variable_get('r4032login_user_register_message', 'You are not authorized to access this page.');
  return '<p>'. t($message) .'</p>';
}
