#! /bin/csh

set UPTIME = `/usr/bin/uptime | awk '{print $10}' | sed s/,//`
if ($UPTIME == "average:") then
  set UPTIME = `/usr/bin/uptime | awk '{print $11}' | sed s/,//`
endif

set CIVDATE = `/bin/date "+%Y:%m:%d:%H:%M"`
set UNIXDATE = `/usr/local/bin/perl -e 'print time()'`

echo $CIVDATE $UNIXDATE $UPTIME
