package edu.berkeley.boinc.rpc;

public class Notice {
	public int seqno = -1;
    public String title = "";
    public String description = "";
    public double create_time;
    public double arrival_time; 
    public boolean is_private;
    public String category = "";
        // assigned by RSS source.  Reserved values:
        // "client": generated by client
        // "server": scheduler RPC message
    public String link = "";
        // URL where original message can be seen, if any
    public String project_name;
        // if notice is associated with a project
    
    public boolean isServerNotice;
    public boolean isClientNotice;
}
