#!/bin/sh

#
# Script to launch java applications in a BOINC environment
#

set +v

libdc-jre=`sed -n '/^<soft_link>/ s/<[^>]*>//gp' libdc-jre.tar`
app-jar=`sed -n '/^<soft_link>/ s/<[^>]*>//gp' Uppercase.jar`

[ -d jre ] || gunzip -c "$libdc-jre" | tar xf -

LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/lib
export LD_LIBRARY_PATH

exec ./jre/bin/java -jar "$app-jar"
