#!/bin/bash

# example of how to create a workunit

# stage the input file
#
bin/stage_file --copy project.xml
if [ $? -ne 0 ]
then
    echo "stage_file failed"
    exit 1
fi

# Run create_work to create the WU.
# The WU name ("wu_nodelete") includes the string "nodelete".
# This causes the file deleter to not delete its input files,
# so that we can use make_work.
#
bin/create_work --appname example_app --wu_name wu_nodelete --wu_template templates/example_app_in --result_template templates/example_app_out project.xml
