# makefile for cuda BOINC example application on Linux.

# Add source files here
EXECUTABLE	:= example_app_nvcuda
# Cuda source files (compiled with cudacc)
CUFILES		:= cuda_kernel.cu
# C/C++ source files (compiled with gcc / c++)
CCFILES		:= cuda.cpp\

################################################################################
# Rules and targets

include common.mk
