#!/bin/sh

##
# post-Upgrade Script for Macintosh BOINC Manager for OS X revised 9/5/07
##

echo "initial directory = $PWD"
echo "argument 1 = $1"

cd "$1"

echo "new directory = $PWD"

# Remove boinc.tiff from screensaver if present because it conflicts with new boinc.jpg
rm -f "/Library/Screen Savers/BOINCSaver.saver/Contents/Resources/boinc.tiff"

# Run the Postinstall Application
Contents/Resources/PostInstall.app/Contents/MacOS/PostInstall -part1

# Touch the newly installed bundles so OS recognizes new version numbers
touch "/Applications/BOINCManager.app"
touch "/Library/Screen Savers/BOINCSaver.saver"

# Start BOINC
Contents/Resources/PostInstall.app/Contents/MacOS/PostInstall -part2 &

exit 0
