#!/bin/sh

##
# post-Install Script for Macintosh BOINC Manager for OS X revised 7/2/15
##

echo "Starting BOINC postinstall script"
echo "initial directory = $PWD"
echo "argument 1 = $1"

# Copy acct_mgr_url.xml into BOINC Data directory here so it won't be
# deleted if user later runs standard BOINC installer
if [ -f "Contents/Resources/acct_mgr_url.xml" ]; then
    cp -fp Contents/Resources/acct_mgr_url.xml "/Library/Application Support/BOINC Data/acct_mgr_url.xml"
fi

rm -f /tmp/BOINCInstallLog.txt

# PostInstall.app is in the same directory as the package (BOINC.pkg or GridRepublic.pkg, etc.)
pipath=`dirname "$1"`/PostInstall.app/Contents/MacOS/PostInstall
echo "PostInstall.app path = $pipath"

# Run the Postinstall Application
if [ "${COMMAND_LINE_INSTALL}" = "1" ]; then
"$pipath" -part1 > /tmp/BOINCInstallLog.txt 2>&1
sleep 2
"$pipath" -part2 >> /tmp/BOINCInstallLog.txt 2>&1 &
else
"$pipath" -part1 2>&1 | tee /tmp/BOINCInstallLog.txt
sleep 2
# part2 continues to run after Installer finishes,
# and fails unless we redirect stdout to a file
"$pipath" -part2 >> /tmp/BOINCInstallLog.txt 2>&1 &
fi

exit 0
