#!/bin/sh

##
# post-Install Script for Macintosh BOINC Manager for OS X revised 3/12/14
##

echo "Starting BOINC postinstall script"
echo "initial directory = $PWD"
echo "argument 1 = $1"

# Copy acct_mgr_url.xml into BOINC Data directory here so it won't be 
# deleted if user later runs standard BOINC installer
if [ -f "Contents/Resources/acct_mgr_url.xml" ]; then
    cp -fp Contents/Resources/acct_mgr_url.xml "/Library/Application Support/BOINC Data/acct_mgr_url.xml"
fi

# Run the Postinstall Application
if [ "${COMMAND_LINE_INSTALL}" = "1" ]; then
rm -f /tmp/BOINCInstallLog.txt
"/tmp/PostInstall.app/Contents/MacOS/PostInstall" -part1 >> /tmp/BOINCInstallLog.txt
sleep 2
"/tmp/PostInstall.app/Contents/MacOS/PostInstall" -part2 >> /tmp/BOINCInstallLog.txt &
else
"/tmp/PostInstall.app/Contents/MacOS/PostInstall" -part1
sleep 2
# part2 continues to run after Installer finishes, 
# and fails unless we redirect stdout to a file
"/tmp/PostInstall.app/Contents/MacOS/PostInstall" -part2 >> /tmp/BOINCInstallLog.txt &
fi

exit 0
