#!/bin/sh

##
# Pre-Install / Pre-Upgrade Script for Macintosh BOINC Manager for OS X revised 7/15/18
##

# If we are replacing an earlier GridRepublic installation, fix the data directory name before installing
## We don't customize BOINC Data directory name for branding
## mv -n "/Library/Application Support/GridRepublic Data" "/Library/Application Support/BOINC Data"

# Delete old World Community Grid Skins
##sudo rm -fR /Library/Application\ Support/BOINC\ Data/skins/World\ Community\ Grid/

# Remove any old BOINC Manager and BOINC Screen Saver bundles to guarantee a clean install
rm -fR "/Applications/BOINCManager.app"
rm -fR "/Library/Screen Savers/BOINCSaver.saver"

# Remove any old "BOINC Manager.mo" files before installing "BOINC-Manager.mo" files (or vice-versa)
rm -fR "/Library/Application Support/BOINC Data/locale/"

# Rename any previous nvc_config.xml file to old_nvc_config.xml to allow
# newer_version_startup_check() to compare them
rm -f "/Library/Application Support/BOINC Data/old_nvc_config.xml"
if [ -e "/Library/Application Support/BOINC Data/nvc_config.xml" ]; then
    mv -f "/Library/Application Support/BOINC Data/nvc_config.xml" "/Library/Application Support/BOINC Data/old_nvc_config.xml"
fi
 
exit 0
