name: Android
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '5 12 * * 0'

jobs:
  build:
    name: ${{ matrix.type }}-build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [manager, libs, apps]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "11"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build manager
        if: ${{ success() && matrix.type == 'manager' }}
        run:  |
          ./android/ci_build_manager.sh

      - name: Build libs
        if: ${{ success() && matrix.type == 'libs' }}
        run: ./android/ci_build_libraries.sh

      - name: Build apps
        if: ${{ success() && matrix.type == 'apps' }}
        run: ./android/ci_build_apps.sh

      - name: Prepare artifacts for deploy
        if: ${{ success() && ! contains(matrix.type, 'libs') }}
        run: python ./deploy/prepare_deployment.py android_${{ matrix.type }}

      - name: Upload generic artifacts
        uses: actions/upload-artifact@v2
        if: ${{ ! contains(matrix.type, 'libs') }}
        with:
          name: android_${{ matrix.type }}_${{ github.event.pull_request.head.sha }}
          path: deploy/android_${{ matrix.type }}.7z
      - name: Upload xiaomi manager
        uses: actions/upload-artifact@v2
        if: ${{ contains(matrix.type, 'manager') }}
        with:
          name: android_xiaomi_${{ matrix.type }}_${{ github.event.pull_request.head.sha }}
          path: deploy/android_${{ matrix.type }}_xiaomi.7z
      - name: Upload armv6 only manager
        uses: actions/upload-artifact@v2
        if: ${{ contains(matrix.type, 'manager') }}
        with:
          name: android_armv6_${{ matrix.type }}_${{ github.event.pull_request.head.sha }}
          path: deploy/android_${{ matrix.type }}_armv6.7z

      - name: Upload JUnit Tests Results
        uses: actions/upload-artifact@v2
        if: always() && matrix.type == 'manager'      # run this step even if previous step failed
        with:
          name: Android_tests_results
          path: android/BOINC/app/build/test-results/testDebugUnitTest/TEST-*.xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v2
        if: ${{ success() && matrix.type == 'manager' }}
        with:
          fail_ci_if_error: true
          verbose: false
