name: Linux
on:
  push:
    branches: [ master, cb_action_test ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: ${{ matrix.type }}-build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [libs, server, client]
    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y freeglut3-dev libxmu-dev libxi-dev libfcgi-dev libxss-dev libnotify-dev libxcb-util0-dev libgtk2.0-dev libwebkitgtk-dev mingw-w64 binutils-mingw-w64-i686 binutils-mingw-w64-x86-64 gcc-mingw-w64 gcc-mingw-w64-i686 gcc-mingw-w64-x86-64 g++-mingw-w64 g++-mingw-w64-i686 g++-mingw-w64-x86-64 p7zip-full

      - name: automake
        if: ${{ success() }}
        run: ./_autosetup

      - name: configure libs
        if: ${{ success() && matrix.type == 'libs' }}
        run: ./configure --disable-server --disable-client --disable-manager

      - name: configure server
        if: ${{ success() && matrix.type == 'server' }}
        run: ./configure --enable-server --disable-client --disable-manager

      - name: configure client
        if: ${{ success() && matrix.type == 'client' }}
        run: ./configure --disable-server --enable-client --disable-manager
        
      - name: make
        if: success()
        run: make

      - name: deploy
        if: ${{ success() }}
        run: echo "Would start deployment now"
        #run: ./deploy/prepare_deployment.sh ${BOINC_TYPE} deploy/${BOINC_TYPE}/ && ./deploy/deploy_to_bintray.sh deploy/${BOINC_TYPE}/
