# This file is part of BOINC.
# https://boinc.berkeley.edu
# Copyright (C) 2026 University of California
#
# BOINC is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License
# as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
#
# BOINC is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with BOINC.  If not, see <http://www.gnu.org/licenses/>.

name: Windows cmake
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  AWS_ACCESS_KEY_ID: ${{secrets.S3_ACCESS_KEY}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.S3_SECRET_KEY}}
  AWS_DEFAULT_REGION: us-west-2

jobs:
  cmake:
    name: ${{matrix.configuration}}-${{matrix.platform}}-cmake
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x64, arm64]
        configuration: [Release, Debug]
      fail-fast: false
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 2

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57

      - name: Check if build is running from origin repo
        if: ${{success() && env.AWS_ACCESS_KEY_ID != 0 && env.AWS_SECRET_ACCESS_KEY != 0}}
        run: |
          echo "VCPKG_BINARY_SOURCES=clear;x-aws,s3://vcpkg.cache.boinc/,readwrite" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append

      - name: Check if build is running from fork
        if: ${{success() && (env.AWS_ACCESS_KEY_ID == 0 || env.AWS_SECRET_ACCESS_KEY == 0)}}
        run: |
          echo "VCPKG_BINARY_SOURCES=clear;x-aws-config,no-sign-request;x-aws,s3://vcpkg.cache.boinc/,read" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append

      - name: Fix vcpkg
        run: vcpkg.exe integrate remove

      - name: Build
        if: success()
        run: windows\ci_build_libs_cmake.bat ${{matrix.platform}} ${{matrix.configuration}}

      - name: Prepare logs on failure
        if: ${{failure()}}
        run: |
          python ./deploy/prepare_deployment.py logs

      - name: Upload logs on failure
        if: ${{failure()}}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: windows_logs_cmake_${{matrix.platform}}_${{matrix.configuration}}_${{github.event.pull_request.head.sha}}
          path: deploy/logs.7z
